#!/usr/bin/env bash
# install nginx

apt-get update
apt-get install -y nginx

# Create default page
echo "Hello World!" > /var/www/html/index.html

# Configurate server
ufw allow 'Nginx HTTP'

service nginx restart

