#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the servers active IPv4 IPs
sudo sed -i '1 i\ \tserver { listen 80; }' /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
