#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
sudo sed -i '1 i\ \tserver { listen 80; }' /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
