#!/usr/bin/env bash
# this script is to displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example) 

ls
