#!/usr/bin/env bash
# nginx must be running as nginx user
sudo apt-get update
sudo apt-get install nginx
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80;/8080;/g' /etc/nginx/sites-available/default 
pkill apache2
sudo -u nginx service nginx start
